AWSTemplateFormatVersion: '2010-09-09'
Description: 'Transit Gateway Attachment - Connect VPC to Transit Gateway'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName
          - VPCType
      - Label:
          default: 'Transit Gateway Configuration'
        Parameters:
          - TransitGatewayId
          - TransitGatewayRouteTableId
      - Label:
          default: 'VPC Configuration'
        Parameters:
          - VPCId
          - SubnetIds

Parameters:
  EnvironmentName:
    Type: String
    Description: 'Environment name (dev, staging, production)'
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

  ProjectName:
    Type: String
    Description: 'Project name'
    Default: niigata-kaigo

  VPCType:
    Type: String
    Description: 'VPC Type (common or app)'
    AllowedValues:
      - common
      - app
    Default: common

  TransitGatewayId:
    Type: String
    Description: 'Transit Gateway ID'

  TransitGatewayRouteTableId:
    Type: String
    Description: 'Transit Gateway Route Table ID'

  VPCId:
    Type: String
    Description: 'VPC ID to attach to Transit Gateway'

  SubnetIds:
    Type: CommaDelimitedList
    Description: 'Comma-delimited list of subnet IDs for Transit Gateway attachment (must be in different AZs)'

Resources:
  # ==========================================================================
  # Transit Gateway Attachment
  # ==========================================================================
  TransitGatewayAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId: !Ref TransitGatewayId
      VpcId: !Ref VPCId
      SubnetIds: !Ref SubnetIds
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-attach-${VPCType}'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: !Ref VPCType
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Transit Gateway Route Table Association
  # ==========================================================================
  TransitGatewayRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableId

  # ==========================================================================
  # Transit Gateway Route Table Propagation
  # ==========================================================================
  TransitGatewayRouteTablePropagation:
    Type: AWS::EC2::TransitGatewayRouteTablePropagation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachment
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableId

Outputs:
  TransitGatewayAttachmentId:
    Description: 'Transit Gateway Attachment ID'
    Value: !Ref TransitGatewayAttachment
    Export:
      Name: !Sub '${AWS::StackName}-TransitGatewayAttachmentId'
