AWSTemplateFormatVersion: '2010-09-09'
Description: 'NAT Gateways Stack for Niigata Kaigo Subsystem - Staging Environment (Single-AZ for cost savings)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Stack Dependencies'
        Parameters:
          - VPCStackName
          - SubnetsStackName
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName

Parameters:
  VPCStackName:
    Type: String
    Default: niigata-kaigo-stg-vpc-core-stack
    Description: Name of the VPC Core stack

  SubnetsStackName:
    Type: String
    Default: niigata-kaigo-stg-subnets-stack
    Description: Name of the Subnets stack

  EnvironmentName:
    Type: String
    Default: staging
    Description: Environment name

  ProjectName:
    Type: String
    Default: niigata-kaigo
    Description: Project name for tagging

Resources:
  # ========================================
  # Elastic IP for NAT Gateway (Single-AZ)
  # ========================================

  NATGatewayEIP1a:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-eip-1a'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation
        - Key: AZ
          Value: ap-northeast-1a

  # ========================================
  # NAT Gateway (Single-AZ for Staging)
  # ========================================

  NATGateway1a:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP1a.AllocationId
      SubnetId: !ImportValue
        Fn::Sub: '${SubnetsStackName}-PublicSubnet1aId'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-gw-1a'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation
        - Key: AZ
          Value: ap-northeast-1a

Outputs:
  # NAT Gateway ID
  NATGateway1aId:
    Description: NAT Gateway 1a ID
    Value: !Ref NATGateway1a
    Export:
      Name: !Sub '${AWS::StackName}-NATGateway1aId'

  # Elastic IP Address
  NATGatewayEIP1a:
    Description: NAT Gateway 1a Elastic IP
    Value: !Ref NATGatewayEIP1a
    Export:
      Name: !Sub '${AWS::StackName}-NATGatewayEIP1a'
