AWSTemplateFormatVersion: '2010-09-09'
Description: 'Subnets Stack for Niigata Kaigo Subsystem - Staging Environment'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Stack Dependencies'
        Parameters:
          - VPCStackName
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName

Parameters:
  VPCStackName:
    Type: String
    Default: niigata-kaigo-stg-vpc-core-stack
    Description: Name of the VPC Core stack to import values from

  EnvironmentName:
    Type: String
    Default: staging
    Description: Environment name

  ProjectName:
    Type: String
    Default: niigata-kaigo
    Description: Project name for tagging

Resources:
  # ========================================
  # Public Subnets
  # ========================================

  PublicSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      CidrBlock: 10.2.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-public-subnet-1a'
        - Key: Type
          Value: Public
        - Key: AZ
          Value: ap-northeast-1a
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  PublicSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      CidrBlock: 10.2.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-public-subnet-1c'
        - Key: Type
          Value: Public
        - Key: AZ
          Value: ap-northeast-1c
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # Private App Subnets
  # ========================================

  PrivateAppSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      CidrBlock: 10.2.11.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-private-app-subnet-1a'
        - Key: Type
          Value: Private
        - Key: Layer
          Value: Application
        - Key: AZ
          Value: ap-northeast-1a
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  PrivateAppSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      CidrBlock: 10.2.12.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-private-app-subnet-1c'
        - Key: Type
          Value: Private
        - Key: Layer
          Value: Application
        - Key: AZ
          Value: ap-northeast-1c
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # Private DB Subnets
  # ========================================

  PrivateDBSubnet1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      CidrBlock: 10.2.21.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-private-db-subnet-1a'
        - Key: Type
          Value: Private
        - Key: Layer
          Value: Database
        - Key: AZ
          Value: ap-northeast-1a
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  PrivateDBSubnet1c:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      CidrBlock: 10.2.22.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-private-db-subnet-1c'
        - Key: Type
          Value: Private
        - Key: Layer
          Value: Database
        - Key: AZ
          Value: ap-northeast-1c
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  # Public Subnets
  PublicSubnet1aId:
    Description: Public Subnet 1a ID
    Value: !Ref PublicSubnet1a
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet1aId'

  PublicSubnet1cId:
    Description: Public Subnet 1c ID
    Value: !Ref PublicSubnet1c
    Export:
      Name: !Sub '${AWS::StackName}-PublicSubnet1cId'

  # Private App Subnets
  PrivateAppSubnet1aId:
    Description: Private App Subnet 1a ID
    Value: !Ref PrivateAppSubnet1a
    Export:
      Name: !Sub '${AWS::StackName}-PrivateAppSubnet1aId'

  PrivateAppSubnet1cId:
    Description: Private App Subnet 1c ID
    Value: !Ref PrivateAppSubnet1c
    Export:
      Name: !Sub '${AWS::StackName}-PrivateAppSubnet1cId'

  # Private DB Subnets
  PrivateDBSubnet1aId:
    Description: Private DB Subnet 1a ID
    Value: !Ref PrivateDBSubnet1a
    Export:
      Name: !Sub '${AWS::StackName}-PrivateDBSubnet1aId'

  PrivateDBSubnet1cId:
    Description: Private DB Subnet 1c ID
    Value: !Ref PrivateDBSubnet1c
    Export:
      Name: !Sub '${AWS::StackName}-PrivateDBSubnet1cId'
