AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito Identity Pool with IAM Roles for Authenticated Users'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Default: kaigo-subsys
    Description: Project name for resource naming

  Environment:
    Type: String
    AllowedValues:
      - prod
      - stg
    Description: Environment name

  IdentityPoolName:
    Type: String
    Description: Cognito Identity Pool Name

  AllowUnauthenticatedIdentities:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'false'
    Description: Allow unauthenticated identities

  UserPoolId:
    Type: String
    Description: Cognito User Pool ID

  UserPoolClientId:
    Type: String
    Description: Cognito User Pool Client ID

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ------------------------------------------------------------------------------
  # Cognito Identity Pool
  # 目的: CognitoユーザーにAWSの一時認証情報（STS）を発行
  # 影響: S3、API Gatewayなど、AWS リソースへのアクセスを制御
  # 前提: 未認証ユーザーは許可しない（セキュリティ要件）
  # ------------------------------------------------------------------------------
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: !Ref AllowUnauthenticatedIdentities
      AllowClassicFlow: false

      # Cognito User Pool を認証プロバイダーとして設定
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClientId
          ProviderName: !Sub cognito-idp.${AWS::Region}.amazonaws.com/${UserPoolId}
          ServerSideTokenCheck: true

  # ------------------------------------------------------------------------------
  # 認証済みユーザー用IAMロール
  # 目的: 認証済みユーザーがAWSリソースにアクセスするための権限
  # 影響: S3（ドキュメントアップロード）、API Gateway（API呼び出し）
  # 前提: 最小権限の原則、ユーザーごとにS3パスを分離（${cognito-identity.amazonaws.com:sub}）
  # ------------------------------------------------------------------------------
  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${ProjectName}-${Environment}-cognito-authenticated-role
      Description: IAM Role for authenticated Cognito users
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref IdentityPool
              ForAnyValue:StringLike:
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        # S3アクセス権限（ドキュメントアップロード用）
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${ProjectName}-${Environment}-user-uploads/${!cognito-identity.amazonaws.com:sub}/*
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${ProjectName}-${Environment}-user-uploads
                Condition:
                  StringLike:
                    s3:prefix:
                      - ${cognito-identity.amazonaws.com:sub}/*

        # API Gateway アクセス権限
        - PolicyName: ApiGatewayAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - execute-api:Invoke
                Resource:
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/GET/*
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/POST/*
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/PUT/*
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/DELETE/*

        # CloudWatch Logs アクセス権限（クライアント側ログ送信用、オプション）
        - PolicyName: CloudWatchLogsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/cognito/${ProjectName}-${Environment}-client-logs:*

      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${Environment}-cognito-authenticated-role
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # ------------------------------------------------------------------------------
  # Identity Pool Role Attachment
  # 目的: Identity PoolとIAMロールを紐付ける
  # 影響: 認証済みユーザーが AuthenticatedRole を使用できるようになる
  # 前提: 未認証ユーザーは許可しないため、UnauthenticatedRoleは未定義
  # ------------------------------------------------------------------------------
  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  IdentityPoolId:
    Description: Cognito Identity Pool ID
    Value: !Ref IdentityPool
    Export:
      Name: !Sub ${ProjectName}-${Environment}-IdentityPoolId

  AuthenticatedRoleArn:
    Description: Authenticated IAM Role ARN
    Value: !GetAtt AuthenticatedRole.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-AuthenticatedRoleArn
