AWSTemplateFormatVersion: '2010-09-09'
Description: 'Cognito User Pool with MFA, Password Policy, and Custom Attributes'

# ==============================================================================
# Parameters
# ==============================================================================
Parameters:
  ProjectName:
    Type: String
    Default: kaigo-subsys
    Description: Project name for resource naming

  Environment:
    Type: String
    AllowedValues:
      - prod
      - stg
    Description: Environment name

  UserPoolName:
    Type: String
    Description: Cognito User Pool Name

  UserPoolDomain:
    Type: String
    Description: Cognito User Pool Domain Prefix

  MfaConfiguration:
    Type: String
    AllowedValues:
      - REQUIRED
      - OPTIONAL
      - OFF
    Default: REQUIRED
    Description: MFA Configuration

  PasswordMinLength:
    Type: Number
    Default: 12
    MinValue: 8
    MaxValue: 99
    Description: Minimum password length

  PasswordRequireUppercase:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Require uppercase letters

  PasswordRequireLowercase:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Require lowercase letters

  PasswordRequireNumbers:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Require numbers

  PasswordRequireSymbols:
    Type: String
    AllowedValues:
      - 'true'
      - 'false'
    Default: 'true'
    Description: Require symbols

  TemporaryPasswordValidityDays:
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 7
    Description: Temporary password validity in days

  AccessTokenValidity:
    Type: Number
    Default: 30
    Description: Access token validity in minutes

  IdTokenValidity:
    Type: Number
    Default: 30
    Description: ID token validity in minutes

  RefreshTokenValidity:
    Type: Number
    Default: 30
    Description: Refresh token validity in days

  PreAuthFunctionArn:
    Type: String
    Description: PreAuthentication Lambda Function ARN

  PostAuthFunctionArn:
    Type: String
    Description: PostAuthentication Lambda Function ARN

  PostConfirmFunctionArn:
    Type: String
    Description: PostConfirmation Lambda Function ARN

  PreTokenFunctionArn:
    Type: String
    Description: PreTokenGeneration Lambda Function ARN

  CustomMessageFunctionArn:
    Type: String
    Description: CustomMessage Lambda Function ARN

# ==============================================================================
# Conditions
# ==============================================================================
Conditions:
  IsProduction: !Equals [!Ref Environment, prod]

# ==============================================================================
# Resources
# ==============================================================================
Resources:
  # ------------------------------------------------------------------------------
  # Cognito User Pool
  # 目的: ユーザー認証・認可の中心的なリソース
  # 影響: すべてのユーザーアカウントを管理、MFA・パスワードポリシーを強制
  # 前提: GCAS準拠のパスワードポリシー、MFA必須
  # ------------------------------------------------------------------------------
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName

      # サインイン設定
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false

      # パスワードポリシー（GCAS準拠）
      Policies:
        PasswordPolicy:
          MinimumLength: !Ref PasswordMinLength
          RequireUppercase: !Ref PasswordRequireUppercase
          RequireLowercase: !Ref PasswordRequireLowercase
          RequireNumbers: !Ref PasswordRequireNumbers
          RequireSymbols: !Ref PasswordRequireSymbols
          TemporaryPasswordValidityDays: !Ref TemporaryPasswordValidityDays

      # MFA設定
      MfaConfiguration: !Ref MfaConfiguration
      EnabledMfas:
        - SOFTWARE_TOKEN_MFA
        - SMS_MFA

      # アカウント復旧設定
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1

      # メール検証設定
      AutoVerifiedAttributes:
        - email
      EmailVerificationMessage: |
        【新潟市介護保険事業所システム】

        メールアドレスの確認コード: {####}

        このコードを15分以内に入力してください。
      EmailVerificationSubject: '【新潟市介護保険事業所システム】メールアドレス確認'

      # ユーザー属性スキーマ
      Schema:
        # 標準属性
        - Name: email
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: phone_number
          AttributeDataType: String
          Required: false
          Mutable: true
        - Name: name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: family_name
          AttributeDataType: String
          Required: true
          Mutable: true
        - Name: given_name
          AttributeDataType: String
          Required: true
          Mutable: true

        # カスタム属性
        - Name: organizationId
          AttributeDataType: String
          Mutable: false
          Required: false
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name: organizationName
          AttributeDataType: String
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name: role
          AttributeDataType: String
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name: employeeId
          AttributeDataType: String
          Mutable: false
          Required: false
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name: department
          AttributeDataType: String
          Mutable: true
          Required: false
          StringAttributeConstraints:
            MinLength: 1
            MaxLength: 256
        - Name: passwordLastChanged
          AttributeDataType: Number
          Mutable: true
          Required: false
          NumberAttributeConstraints:
            MinValue: 0

      # Lambda トリガー
      LambdaConfig:
        PreAuthentication: !Ref PreAuthFunctionArn
        PostAuthentication: !Ref PostAuthFunctionArn
        PostConfirmation: !Ref PostConfirmFunctionArn
        PreTokenGeneration: !Ref PreTokenFunctionArn
        CustomMessage: !Ref CustomMessageFunctionArn

      # ユーザープール削除保護（本番のみ）
      DeletionProtection: !If [IsProduction, ACTIVE, INACTIVE]

      # デバイス記憶設定
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: true

      # タグ
      UserPoolTags:
        Name: !Ref UserPoolName
        Project: !Ref ProjectName
        Environment: !Ref Environment
        ManagedBy: CloudFormation

  # ------------------------------------------------------------------------------
  # User Pool Domain
  # 目的: Cognito Hosted UIのドメイン設定
  # 影響: ログイン画面のURLが決まる
  # 前提: カスタムドメインは将来的に検討
  # ------------------------------------------------------------------------------
  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref UserPoolDomain
      UserPoolId: !Ref UserPool

  # ------------------------------------------------------------------------------
  # User Pool Client（アプリクライアント）
  # 目的: フロントエンド（Next.js）からCognitoにアクセスするためのクライアント設定
  # 影響: トークンの有効期限、認証フローが決まる
  # 前提: SRP認証（Secure Remote Password）を使用
  # ------------------------------------------------------------------------------
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub ${ProjectName}-${Environment}-web-client
      UserPoolId: !Ref UserPool

      # 認証フロー設定
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH

      # トークン有効期限
      AccessTokenValidity: !Ref AccessTokenValidity
      IdTokenValidity: !Ref IdTokenValidity
      RefreshTokenValidity: !Ref RefreshTokenValidity
      TokenValidityUnits:
        AccessToken: minutes
        IdToken: minutes
        RefreshToken: days

      # セキュリティ設定
      PreventUserExistenceErrors: ENABLED
      EnableTokenRevocation: true

      # OAuth設定
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true

      # コールバックURL（環境別）
      CallbackURLs:
        - !If
          - IsProduction
          - https://kaigo-subsys.niigata.lg.jp/callback
          - https://kaigo-subsys-stg.niigata.lg.jp/callback
      LogoutURLs:
        - !If
          - IsProduction
          - https://kaigo-subsys.niigata.lg.jp/logout
          - https://kaigo-subsys-stg.niigata.lg.jp/logout

      # 属性の読み取り・書き込み権限
      ReadAttributes:
        - email
        - email_verified
        - name
        - family_name
        - given_name
        - phone_number
        - phone_number_verified
        - custom:organizationId
        - custom:organizationName
        - custom:role
        - custom:employeeId
        - custom:department
      WriteAttributes:
        - email
        - name
        - family_name
        - given_name
        - phone_number
        - custom:organizationName
        - custom:role
        - custom:department
        - custom:passwordLastChanged

  # ------------------------------------------------------------------------------
  # Lambda Invocation Permissions
  # 目的: CognitoがLambda関数を呼び出せるようにする
  # 影響: Lambda トリガーが動作するために必須
  # 前提: 各Lambda関数に対して個別に権限を付与
  # ------------------------------------------------------------------------------
  PreAuthInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PreAuthFunctionArn
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt UserPool.Arn

  PostAuthInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostAuthFunctionArn
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt UserPool.Arn

  PostConfirmInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostConfirmFunctionArn
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt UserPool.Arn

  PreTokenInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PreTokenFunctionArn
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt UserPool.Arn

  CustomMessageInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CustomMessageFunctionArn
      Principal: cognito-idp.amazonaws.com
      Action: lambda:InvokeFunction
      SourceArn: !GetAtt UserPool.Arn

# ==============================================================================
# Outputs
# ==============================================================================
Outputs:
  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub ${ProjectName}-${Environment}-UserPoolId

  UserPoolArn:
    Description: Cognito User Pool ARN
    Value: !GetAtt UserPool.Arn
    Export:
      Name: !Sub ${ProjectName}-${Environment}-UserPoolArn

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub ${ProjectName}-${Environment}-UserPoolClientId

  UserPoolDomain:
    Description: Cognito User Pool Domain
    Value: !Ref UserPoolDomain
    Export:
      Name: !Sub ${ProjectName}-${Environment}-UserPoolDomainName

  HostedUIUrl:
    Description: Cognito Hosted UI URL
    Value: !Sub https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com
    Export:
      Name: !Sub ${ProjectName}-${Environment}-HostedUIUrl
