AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Fargate Cluster with Backend (.NET Core) and Frontend (Next.js) services'

Parameters:
  EnvironmentName:
    Type: String
    Description: Environment name (dev, staging, production)
    AllowedValues:
      - dev
      - staging
      - production

  ProjectName:
    Type: String
    Description: Project name for resource naming

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: Comma-delimited list of private subnet IDs for ECS tasks

  ECSSecurityGroupId:
    Type: String
    Description: Security Group ID for ECS tasks

  BackendTargetGroupArn:
    Type: String
    Description: ARN of the Backend Target Group

  FrontendTargetGroupArn:
    Type: String
    Description: ARN of the Frontend Target Group

  # Backend Task Configuration
  BackendTaskCpu:
    Type: String
    Description: CPU units for Backend task (256, 512, 1024, 2048, 4096)
    Default: "512"
    AllowedValues:
      - "256"
      - "512"
      - "1024"
      - "2048"
      - "4096"

  BackendTaskMemory:
    Type: String
    Description: Memory for Backend task (MB)
    Default: "1024"
    AllowedValues:
      - "512"
      - "1024"
      - "2048"
      - "4096"
      - "8192"

  BackendImageUri:
    Type: String
    Description: Docker image URI for Backend (.NET Core)
    Default: "public.ecr.aws/docker/library/nginx:latest"  # Placeholder

  BackendDesiredCount:
    Type: Number
    Description: Desired number of Backend tasks
    Default: 2
    MinValue: 1
    MaxValue: 10

  # Frontend Task Configuration
  FrontendTaskCpu:
    Type: String
    Description: CPU units for Frontend task
    Default: "256"
    AllowedValues:
      - "256"
      - "512"
      - "1024"
      - "2048"
      - "4096"

  FrontendTaskMemory:
    Type: String
    Description: Memory for Frontend task (MB)
    Default: "512"
    AllowedValues:
      - "512"
      - "1024"
      - "2048"
      - "4096"
      - "8192"

  FrontendImageUri:
    Type: String
    Description: Docker image URI for Frontend (Next.js)
    Default: "public.ecr.aws/docker/library/nginx:latest"  # Placeholder

  FrontendDesiredCount:
    Type: Number
    Description: Desired number of Frontend tasks
    Default: 2
    MinValue: 1
    MaxValue: 10

  # Database Connection (from Secrets Manager)
  DBSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing DB credentials
    Default: ""

  # Redis Connection (from Secrets Manager)
  RedisSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing Redis AUTH token
    Default: ""

  # CloudWatch Logs Retention
  LogRetentionDays:
    Type: Number
    Description: CloudWatch Logs retention period in days (GCAS requires 90+ days)
    Default: 90
    AllowedValues:
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653

Conditions:
  HasDBSecret: !Not [!Equals [!Ref DBSecretArn, ""]]
  HasRedisSecret: !Not [!Equals [!Ref RedisSecretArn, ""]]

Resources:
  # ==============================================================================
  # ECS Cluster
  # ==============================================================================
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${ProjectName}-${EnvironmentName}-cluster'
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-cluster'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # IAM Roles
  # ==============================================================================
  # Task Execution Role (for ECS to pull images and send logs)
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${EnvironmentName}-ecs-task-execution-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - !If
          - HasDBSecret
          - PolicyName: SecretsManagerAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - secretsmanager:GetSecretValue
                  Resource: !If
                    - HasRedisSecret
                    - - !Ref DBSecretArn
                      - !Ref RedisSecretArn
                    - - !Ref DBSecretArn
          - !Ref AWS::NoValue
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-ecs-task-execution-role'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # Task Role (for application code)
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${EnvironmentName}-ecs-task-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${ProjectName}-${EnvironmentName}-app-data/*'
                  - !Sub 'arn:aws:s3:::${ProjectName}-${EnvironmentName}-app-data'
        - PolicyName: CloudWatchMetrics
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-ecs-task-role'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # CloudWatch Log Groups
  # ==============================================================================
  BackendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-${EnvironmentName}-backend'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-backend-logs'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  FrontendLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/ecs/${ProjectName}-${EnvironmentName}-frontend'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-frontend-logs'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # Backend Task Definition (.NET Core)
  # ==============================================================================
  BackendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${EnvironmentName}-backend'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref BackendTaskCpu
      Memory: !Ref BackendTaskMemory
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: backend
          Image: !Ref BackendImageUri
          Essential: true
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          Environment:
            - Name: ASPNETCORE_ENVIRONMENT
              Value: !Ref EnvironmentName
            - Name: ASPNETCORE_URLS
              Value: "http://+:8080"
          Secrets: !If
            - HasDBSecret
            - !If
              - HasRedisSecret
              - - Name: DB_CONNECTION_STRING
                  ValueFrom: !Sub '${DBSecretArn}:connectionString::'
                - Name: REDIS_CONNECTION_STRING
                  ValueFrom: !Sub '${RedisSecretArn}:connectionString::'
              - - Name: DB_CONNECTION_STRING
                  ValueFrom: !Sub '${DBSecretArn}:connectionString::'
            - !Ref AWS::NoValue
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref BackendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:8080/health || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-backend-task'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # Frontend Task Definition (Next.js)
  # ==============================================================================
  FrontendTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub '${ProjectName}-${EnvironmentName}-frontend'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !Ref FrontendTaskCpu
      Memory: !Ref FrontendTaskMemory
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: frontend
          Image: !Ref FrontendImageUri
          Essential: true
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: NEXT_PUBLIC_API_URL
              Value: !Sub 'https://${ProjectName}-${EnvironmentName}.example.com/api'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref FrontendLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - curl -f http://localhost:3000/ || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-frontend-task'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # Backend ECS Service
  # ==============================================================================
  BackendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ProjectName}-${EnvironmentName}-backend-service'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref BackendTaskDefinition
      DesiredCount: !Ref BackendDesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref PrivateSubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroupId
      LoadBalancers:
        - ContainerName: backend
          ContainerPort: 8080
          TargetGroupArn: !Ref BackendTargetGroupArn
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-backend-service'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # Frontend ECS Service
  # ==============================================================================
  FrontendService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub '${ProjectName}-${EnvironmentName}-frontend-service'
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref FrontendTaskDefinition
      DesiredCount: !Ref FrontendDesiredCount
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref PrivateSubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroupId
      LoadBalancers:
        - ContainerName: frontend
          ContainerPort: 3000
          TargetGroupArn: !Ref FrontendTargetGroupArn
      HealthCheckGracePeriodSeconds: 60
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true
          Rollback: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-frontend-service'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName

  # ==============================================================================
  # Auto Scaling
  # ==============================================================================
  # Backend Auto Scaling Target
  BackendAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub 'service/${ECSCluster}/${BackendService.Name}'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # Backend CPU Scaling Policy
  BackendCPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${EnvironmentName}-backend-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref BackendAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70.0
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

  # Frontend Auto Scaling Target
  FrontendAutoScalingTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub 'service/${ECSCluster}/${FrontendService.Name}'
      RoleARN: !Sub 'arn:aws:iam::${AWS::AccountId}:role/aws-service-role/ecs.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_ECSService'
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  # Frontend CPU Scaling Policy
  FrontendCPUScalingPolicy:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Sub '${ProjectName}-${EnvironmentName}-frontend-cpu-scaling'
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref FrontendAutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 70.0
        ScaleInCooldown: 300
        ScaleOutCooldown: 60

Outputs:
  ClusterArn:
    Description: ARN of the ECS Cluster
    Value: !GetAtt ECSCluster.Arn
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-ecs-cluster-arn'

  ClusterName:
    Description: Name of the ECS Cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-ecs-cluster-name'

  BackendServiceName:
    Description: Name of the Backend ECS Service
    Value: !GetAtt BackendService.Name
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-backend-service-name'

  FrontendServiceName:
    Description: Name of the Frontend ECS Service
    Value: !GetAtt FrontendService.Name
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-frontend-service-name'

  BackendLogGroupName:
    Description: CloudWatch Log Group for Backend
    Value: !Ref BackendLogGroup
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-backend-log-group'

  FrontendLogGroupName:
    Description: CloudWatch Log Group for Frontend
    Value: !Ref FrontendLogGroup
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-frontend-log-group'

  TaskExecutionRoleArn:
    Description: ARN of the Task Execution Role
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-task-execution-role-arn'

  TaskRoleArn:
    Description: ARN of the Task Role
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-task-role-arn'
