AWSTemplateFormatVersion: '2010-09-09'
Description: 'App Account Network Stack - App VPC + Transit Gateway Attachment'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName
      - Label:
          default: 'VPC CIDR Configuration'
        Parameters:
          - AppVPCCidr
      - Label:
          default: 'Transit Gateway Configuration (from Common Account)'
        Parameters:
          - TransitGatewayId
          - TransitGatewayRouteTableId
      - Label:
          default: 'Template Storage'
        Parameters:
          - TemplateBucketName

Parameters:
  EnvironmentName:
    Type: String
    Description: 'Environment name (dev, staging, production)'
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

  ProjectName:
    Type: String
    Description: 'Project name'
    Default: niigata-kaigo

  AppVPCCidr:
    Type: String
    Description: 'App VPC CIDR block'
    Default: 10.101.0.0/16
    AllowedPattern: ^(10\.\d{1,3}\.\d{1,3}\.\d{1,3}\/16)$

  TransitGatewayId:
    Type: String
    Description: 'Transit Gateway ID (shared from Common Account)'
    Default: ''

  TransitGatewayRouteTableId:
    Type: String
    Description: 'Transit Gateway Route Table ID for App VPC (shared from Common Account)'
    Default: ''

  TemplateBucketName:
    Type: String
    Description: 'S3 bucket name for nested stack templates'
    Default: niigata-kaigo-cfn-templates-dev

Conditions:
  AttachToTransitGateway: !Not [!Equals [!Ref TransitGatewayId, '']]

Resources:
  # ==========================================================================
  # App VPC + Internet Gateway
  # ==========================================================================
  AppVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/appアカウント/templates/network/vpc-and-igw.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        VPCCidr: !Ref AppVPCCidr
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-vpc-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC Subnets
  # ==========================================================================
  AppSubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppVPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/appアカウント/templates/network/subnets.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        VPCId: !GetAtt AppVPCStack.Outputs.VPCId
        VPCCidr: !Ref AppVPCCidr
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-subnets-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC NAT Gateways
  # ==========================================================================
  AppNATGatewaysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppSubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/appアカウント/templates/network/nat-gateways.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        PublicSubnet1Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Transit Gateway Attachment - App VPC
  # ==========================================================================
  AppTGWAttachmentStack:
    Type: AWS::CloudFormation::Stack
    Condition: AttachToTransitGateway
    DependsOn: AppSubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/appアカウント/templates/network/transit-gateway-attachment.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCType: app
        TransitGatewayId: !Ref TransitGatewayId
        TransitGatewayRouteTableId: !Ref TransitGatewayRouteTableId
        VPCId: !GetAtt AppVPCStack.Outputs.VPCId
        SubnetIds: !Join
          - ','
          - - !GetAtt AppSubnetsStack.Outputs.PrivateSubnet1Id
            - !GetAtt AppSubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-attach-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC Route Tables (with TGW routes if attached)
  # ==========================================================================
  AppRouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AppVPCStack
      - AppSubnetsStack
      - AppNATGatewaysStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/appアカウント/templates/network/route-tables.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        VPCId: !GetAtt AppVPCStack.Outputs.VPCId
        InternetGatewayId: !GetAtt AppVPCStack.Outputs.InternetGatewayId
        NATGateway1Id: !GetAtt AppNATGatewaysStack.Outputs.NATGateway1Id
        NATGateway2Id: !GetAtt AppNATGatewaysStack.Outputs.NATGateway2Id
        PublicSubnet1Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-rt-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  # App VPC Outputs
  AppVPCId:
    Description: 'App VPC ID'
    Value: !GetAtt AppVPCStack.Outputs.VPCId
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppVpcId'

  AppVPCCidr:
    Description: 'App VPC CIDR'
    Value: !Ref AppVPCCidr
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppVpcCidr'

  AppPrivateSubnet1Id:
    Description: 'App VPC Private Subnet 1 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPrivateSubnet1Id'

  AppPrivateSubnet2Id:
    Description: 'App VPC Private Subnet 2 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPrivateSubnet2Id'

  AppPublicSubnet1Id:
    Description: 'App VPC Public Subnet 1 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PublicSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPublicSubnet1Id'

  AppPublicSubnet2Id:
    Description: 'App VPC Public Subnet 2 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PublicSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPublicSubnet2Id'
