AWSTemplateFormatVersion: '2010-09-09'
Description: 'NAT Gateways Stack for Niigata Kaigo Subsystem'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Subnet Configuration'
        Parameters:
          - PublicSubnet1Id
          - PublicSubnet2Id
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName

Parameters:
  PublicSubnet1Id:
    Type: String
    Description: Public Subnet 1 ID

  PublicSubnet2Id:
    Type: String
    Description: Public Subnet 2 ID

  EnvironmentName:
    Type: String
    Description: Environment name

  ProjectName:
    Type: String
    Description: Project name for tagging

Resources:
  # ========================================
  # Elastic IPs for NAT Gateways
  # ========================================

  NATGatewayEIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-eip-1'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  NATGatewayEIP2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-eip-2'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # NAT Gateways (Multi-AZ)
  # ========================================

  NATGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP1.AllocationId
      SubnetId: !Ref PublicSubnet1Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-gw-1'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  NATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NATGatewayEIP2.AllocationId
      SubnetId: !Ref PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-gw-2'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  # NAT Gateway IDs
  NATGateway1Id:
    Description: NAT Gateway 1 ID
    Value: !Ref NATGateway1
    Export:
      Name: !Sub '${AWS::StackName}-NATGateway1Id'

  NATGateway2Id:
    Description: NAT Gateway 2 ID
    Value: !Ref NATGateway2
    Export:
      Name: !Sub '${AWS::StackName}-NATGateway2Id'

  # Elastic IP Addresses
  NATGatewayEIP1:
    Description: NAT Gateway 1 Elastic IP
    Value: !Ref NATGatewayEIP1
    Export:
      Name: !Sub '${AWS::StackName}-NATGatewayEIP1'

  NATGatewayEIP2:
    Description: NAT Gateway 2 Elastic IP
    Value: !Ref NATGatewayEIP2
    Export:
      Name: !Sub '${AWS::StackName}-NATGatewayEIP2'
