AWSTemplateFormatVersion: '2010-09-09'
Description: 'Security Groups Stack for Niigata Kaigo Subsystem - Production Environment'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Stack Dependencies'
        Parameters:
          - VPCStackName
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName

Parameters:
  VPCStackName:
    Type: String
    Default: niigata-kaigo-prod-vpc-core-stack
    Description: Name of the VPC Core stack

  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name

  ProjectName:
    Type: String
    Default: niigata-kaigo
    Description: Project name for tagging

Resources:
  # ========================================
  # ALB Security Group
  # ========================================

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${EnvironmentName}-alb-sg'
      GroupDescription: Security Group for Application Load Balancer
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      SecurityGroupIngress:
        # HTTPS from Internet (拠点からのアクセス)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS from Internet
        # HTTP (リダイレクト用)
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
          Description: HTTP for redirect to HTTPS
      SecurityGroupEgress:
        # Allow all outbound
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-alb-sg'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # ECS Security Group
  # ========================================

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${EnvironmentName}-ecs-sg'
      GroupDescription: Security Group for ECS Fargate Tasks
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      SecurityGroupIngress:
        # HTTP from ALB
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroup
          Description: HTTP from ALB
      SecurityGroupEgress:
        # Allow all outbound
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-ecs-sg'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # RDS Security Group
  # ========================================

  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${EnvironmentName}-rds-sg'
      GroupDescription: Security Group for RDS MySQL
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      SecurityGroupIngress:
        # MySQL from ECS
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref ECSSecurityGroup
          Description: MySQL from ECS
      SecurityGroupEgress:
        # Deny all outbound (RDS doesn't need outbound)
        - IpProtocol: -1
          CidrIp: 127.0.0.1/32
          Description: Deny all outbound
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-rds-sg'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # ElastiCache Security Group
  # ========================================

  ElastiCacheSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${EnvironmentName}-elasticache-sg'
      GroupDescription: Security Group for ElastiCache Redis
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      SecurityGroupIngress:
        # Redis from ECS
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref ECSSecurityGroup
          Description: Redis from ECS
      SecurityGroupEgress:
        # Deny all outbound
        - IpProtocol: -1
          CidrIp: 127.0.0.1/32
          Description: Deny all outbound
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-elasticache-sg'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # VPC Endpoint Security Group
  # ========================================

  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ProjectName}-${EnvironmentName}-vpce-sg'
      GroupDescription: Security Group for VPC Endpoints
      VpcId: !ImportValue
        Fn::Sub: '${VPCStackName}-VPCId'
      SecurityGroupIngress:
        # HTTPS from ECS
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !Ref ECSSecurityGroup
          Description: HTTPS from ECS
      SecurityGroupEgress:
        # Allow all outbound
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-vpce-sg'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  ALBSecurityGroupId:
    Description: ALB Security Group ID
    Value: !Ref ALBSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ALBSecurityGroupId'

  ECSSecurityGroupId:
    Description: ECS Security Group ID
    Value: !Ref ECSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ECSSecurityGroupId'

  RDSSecurityGroupId:
    Description: RDS Security Group ID
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-RDSSecurityGroupId'

  ElastiCacheSecurityGroupId:
    Description: ElastiCache Security Group ID
    Value: !Ref ElastiCacheSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-ElastiCacheSecurityGroupId'

  VPCEndpointSecurityGroupId:
    Description: VPC Endpoint Security Group ID
    Value: !Ref VPCEndpointSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-VPCEndpointSecurityGroupId'
