AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network Stack - 2 VPCs (Common + App) with Transit Gateway (Multi-Account ready)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName
      - Label:
          default: 'VPC CIDR Configuration'
        Parameters:
          - CommonVPCCidr
          - AppVPCCidr
      - Label:
          default: 'Transit Gateway Configuration'
        Parameters:
          - EnableTransitGateway
      - Label:
          default: 'Template Storage'
        Parameters:
          - TemplateBucketName

Parameters:
  EnvironmentName:
    Type: String
    Description: 'Environment name (dev, staging, production)'
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

  ProjectName:
    Type: String
    Description: 'Project name'
    Default: niigata-kaigo

  CommonVPCCidr:
    Type: String
    Description: 'Common VPC CIDR block'
    Default: 10.100.0.0/16
    AllowedPattern: ^(10\.\d{1,3}\.\d{1,3}\.\d{1,3}\/16)$

  AppVPCCidr:
    Type: String
    Description: 'App VPC CIDR block'
    Default: 10.101.0.0/16
    AllowedPattern: ^(10\.\d{1,3}\.\d{1,3}\.\d{1,3}\/16)$

  EnableTransitGateway:
    Type: String
    Description: 'Enable Transit Gateway (Yes for multi-VPC, No for single VPC)'
    Default: 'Yes'
    AllowedValues:
      - 'Yes'
      - 'No'

  TemplateBucketName:
    Type: String
    Description: 'S3 bucket name for nested stack templates'
    Default: niigata-kaigo-cfn-templates-dev

Conditions:
  CreateTransitGateway: !Equals [!Ref EnableTransitGateway, 'Yes']

Resources:
  # ==========================================================================
  # Transit Gateway（マルチVPC接続用）
  # ==========================================================================
  TransitGatewayStack:
    Type: AWS::CloudFormation::Stack
    Condition: CreateTransitGateway
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/transit-gateway.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Common VPC + Internet Gateway
  # ==========================================================================
  CommonVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/vpc-and-igw.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-common'
        VPCCidr: !Ref CommonVPCCidr
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-vpc-common-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: common
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC + Internet Gateway
  # ==========================================================================
  AppVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/vpc-and-igw.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        VPCCidr: !Ref AppVPCCidr
        EnableDnsSupport: 'true'
        EnableDnsHostnames: 'true'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-vpc-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Common VPC Subnets
  # ==========================================================================
  CommonSubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CommonVPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/subnets.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-common'
        VPCId: !GetAtt CommonVPCStack.Outputs.VPCId
        VPCCidr: !Ref CommonVPCCidr
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-subnets-common-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: common
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC Subnets
  # ==========================================================================
  AppSubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppVPCStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/subnets.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        VPCId: !GetAtt AppVPCStack.Outputs.VPCId
        VPCCidr: !Ref AppVPCCidr
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-subnets-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Common VPC NAT Gateways
  # ==========================================================================
  CommonNATGatewaysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: CommonSubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/nat-gateways.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-common'
        PublicSubnet1Id: !GetAtt CommonSubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt CommonSubnetsStack.Outputs.PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-common-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: common
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC NAT Gateways
  # ==========================================================================
  AppNATGatewaysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: AppSubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/nat-gateways.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        PublicSubnet1Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-nat-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Transit Gateway Attachment - Common VPC
  # ==========================================================================
  CommonTGWAttachmentStack:
    Type: AWS::CloudFormation::Stack
    Condition: CreateTransitGateway
    DependsOn:
      - TransitGatewayStack
      - CommonSubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/transit-gateway-attachment.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCType: common
        TransitGatewayId: !GetAtt TransitGatewayStack.Outputs.TransitGatewayId
        TransitGatewayRouteTableId: !GetAtt TransitGatewayStack.Outputs.CommonRouteTableId
        VPCId: !GetAtt CommonVPCStack.Outputs.VPCId
        SubnetIds: !Join
          - ','
          - - !GetAtt CommonSubnetsStack.Outputs.PrivateSubnet1Id
            - !GetAtt CommonSubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-attach-common-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: common
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Transit Gateway Attachment - App VPC
  # ==========================================================================
  AppTGWAttachmentStack:
    Type: AWS::CloudFormation::Stack
    Condition: CreateTransitGateway
    DependsOn:
      - TransitGatewayStack
      - AppSubnetsStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/transit-gateway-attachment.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCType: app
        TransitGatewayId: !GetAtt TransitGatewayStack.Outputs.TransitGatewayId
        TransitGatewayRouteTableId: !GetAtt TransitGatewayStack.Outputs.AppRouteTableId
        VPCId: !GetAtt AppVPCStack.Outputs.VPCId
        SubnetIds: !Join
          - ','
          - - !GetAtt AppSubnetsStack.Outputs.PrivateSubnet1Id
            - !GetAtt AppSubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-attach-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Common VPC Route Tables (with TGW routes if enabled)
  # ==========================================================================
  CommonRouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - CommonVPCStack
      - CommonSubnetsStack
      - CommonNATGatewaysStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/route-tables.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-common'
        VPCId: !GetAtt CommonVPCStack.Outputs.VPCId
        InternetGatewayId: !GetAtt CommonVPCStack.Outputs.InternetGatewayId
        NATGateway1Id: !GetAtt CommonNATGatewaysStack.Outputs.NATGateway1Id
        NATGateway2Id: !GetAtt CommonNATGatewaysStack.Outputs.NATGateway2Id
        PublicSubnet1Id: !GetAtt CommonSubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt CommonSubnetsStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt CommonSubnetsStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt CommonSubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-rt-common-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: common
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # App VPC Route Tables (with TGW routes if enabled)
  # ==========================================================================
  AppRouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AppVPCStack
      - AppSubnetsStack
      - AppNATGatewaysStack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${TemplateBucketName}/templates/network/route-tables.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Sub '${ProjectName}-app'
        VPCId: !GetAtt AppVPCStack.Outputs.VPCId
        InternetGatewayId: !GetAtt AppVPCStack.Outputs.InternetGatewayId
        NATGateway1Id: !GetAtt AppNATGatewaysStack.Outputs.NATGateway1Id
        NATGateway2Id: !GetAtt AppNATGatewaysStack.Outputs.NATGateway2Id
        PublicSubnet1Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt AppSubnetsStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-rt-app-stack'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  # Transit Gateway Outputs
  TransitGatewayId:
    Condition: CreateTransitGateway
    Description: 'Transit Gateway ID'
    Value: !GetAtt TransitGatewayStack.Outputs.TransitGatewayId
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-TransitGatewayId'

  # Common VPC Outputs
  CommonVPCId:
    Description: 'Common VPC ID'
    Value: !GetAtt CommonVPCStack.Outputs.VPCId
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-CommonVpcId'

  CommonVPCCidr:
    Description: 'Common VPC CIDR'
    Value: !Ref CommonVPCCidr
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-CommonVpcCidr'

  CommonPrivateSubnet1Id:
    Description: 'Common VPC Private Subnet 1 ID'
    Value: !GetAtt CommonSubnetsStack.Outputs.PrivateSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-CommonPrivateSubnet1Id'

  CommonPrivateSubnet2Id:
    Description: 'Common VPC Private Subnet 2 ID'
    Value: !GetAtt CommonSubnetsStack.Outputs.PrivateSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-CommonPrivateSubnet2Id'

  # App VPC Outputs
  AppVPCId:
    Description: 'App VPC ID'
    Value: !GetAtt AppVPCStack.Outputs.VPCId
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppVpcId'

  AppVPCCidr:
    Description: 'App VPC CIDR'
    Value: !Ref AppVPCCidr
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppVpcCidr'

  AppPrivateSubnet1Id:
    Description: 'App VPC Private Subnet 1 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPrivateSubnet1Id'

  AppPrivateSubnet2Id:
    Description: 'App VPC Private Subnet 2 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PrivateSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPrivateSubnet2Id'

  AppPublicSubnet1Id:
    Description: 'App VPC Public Subnet 1 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PublicSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPublicSubnet1Id'

  AppPublicSubnet2Id:
    Description: 'App VPC Public Subnet 2 ID'
    Value: !GetAtt AppSubnetsStack.Outputs.PublicSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-AppPublicSubnet2Id'
