AWSTemplateFormatVersion: '2010-09-09'
Description: 'Network Stack - VPC, Subnets, NAT Gateways, Route Tables, Security Groups'

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - production
      - staging
    Description: 'Environment name'

  ProjectName:
    Type: String
    Default: 'niigata-kaigo'
    Description: 'Project name for resource naming'

  VpcCidr:
    Type: String
    Description: 'VPC CIDR block'

  PublicSubnet1Cidr:
    Type: String
    Description: 'Public Subnet 1 CIDR'

  PublicSubnet2Cidr:
    Type: String
    Description: 'Public Subnet 2 CIDR'

  PrivateSubnet1Cidr:
    Type: String
    Description: 'Private Subnet 1 CIDR'

  PrivateSubnet2Cidr:
    Type: String
    Description: 'Private Subnet 2 CIDR'

  TemplateBucket:
    Type: String
    Description: 'S3 bucket for nested stack templates'
    Default: 'niigata-kaigo-cfn-templates'

  TemplatePrefix:
    Type: String
    Description: 'S3 prefix for templates'
    Default: 'templates'

Resources:
  # VPC and Internet Gateway（密結合、初回のみ作成）
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}/network/vpc-and-igw.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcCidr: !Ref VpcCidr
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-vpc-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # Subnets（別メニュー、たまに追加）
  SubnetsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}/network/subnets.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        PublicSubnet1Cidr: !Ref PublicSubnet1Cidr
        PublicSubnet2Cidr: !Ref PublicSubnet2Cidr
        PrivateSubnet1Cidr: !Ref PrivateSubnet1Cidr
        PrivateSubnet2Cidr: !Ref PrivateSubnet2Cidr
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-subnets-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # NAT Gateways（高額、初回のみ作成）
  NATGatewaysStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: SubnetsStack
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}/network/nat-gateways.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        PublicSubnet1Id: !GetAtt SubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt SubnetsStack.Outputs.PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-nat-gateways-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # Route Tables（たまに変更）
  RouteTablesStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: NATGatewaysStack
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}/network/route-tables.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGatewayId
        NATGateway1Id: !GetAtt NATGatewaysStack.Outputs.NATGateway1Id
        NATGateway2Id: !GetAtt NATGatewaysStack.Outputs.NATGateway2Id
        PublicSubnet1Id: !GetAtt SubnetsStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt SubnetsStack.Outputs.PublicSubnet2Id
        PrivateSubnet1Id: !GetAtt SubnetsStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt SubnetsStack.Outputs.PrivateSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-route-tables-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

  # Security Groups（激増する可能性、ディレクトリで分割）
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: VPCStack
    Properties:
      TemplateURL: !Sub 'https://${TemplateBucket}.s3.amazonaws.com/${TemplatePrefix}/network/security-groups/main.yaml'
      Parameters:
        Environment: !Ref Environment
        ProjectName: !Ref ProjectName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-security-groups-stack'
        - Key: Environment
          Value: !Ref Environment
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  VpcId:
    Description: 'VPC ID'
    Value: !GetAtt VPCStack.Outputs.VpcId
    Export:
      Name: !Sub '${ProjectName}-${Environment}-VpcId'

  PublicSubnet1Id:
    Description: 'Public Subnet 1 ID'
    Value: !GetAtt SubnetsStack.Outputs.PublicSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PublicSubnet1Id'

  PublicSubnet2Id:
    Description: 'Public Subnet 2 ID'
    Value: !GetAtt SubnetsStack.Outputs.PublicSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PublicSubnet2Id'

  PrivateSubnet1Id:
    Description: 'Private Subnet 1 ID'
    Value: !GetAtt SubnetsStack.Outputs.PrivateSubnet1Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PrivateSubnet1Id'

  PrivateSubnet2Id:
    Description: 'Private Subnet 2 ID'
    Value: !GetAtt SubnetsStack.Outputs.PrivateSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PrivateSubnet2Id'

  PublicSubnetIds:
    Description: 'Public Subnet IDs (comma-separated)'
    Value: !Sub
      - '${Subnet1},${Subnet2}'
      - Subnet1: !GetAtt SubnetsStack.Outputs.PublicSubnet1Id
        Subnet2: !GetAtt SubnetsStack.Outputs.PublicSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PublicSubnetIds'

  PrivateSubnetIds:
    Description: 'Private Subnet IDs (comma-separated)'
    Value: !Sub
      - '${Subnet1},${Subnet2}'
      - Subnet1: !GetAtt SubnetsStack.Outputs.PrivateSubnet1Id
        Subnet2: !GetAtt SubnetsStack.Outputs.PrivateSubnet2Id
    Export:
      Name: !Sub '${ProjectName}-${Environment}-PrivateSubnetIds'

  ALBSecurityGroupId:
    Description: 'ALB Security Group ID'
    Value: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroupId
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ALBSecurityGroupId'

  ECSSecurityGroupId:
    Description: 'ECS Security Group ID'
    Value: !GetAtt SecurityGroupsStack.Outputs.ECSSecurityGroupId
    Export:
      Name: !Sub '${ProjectName}-${Environment}-ECSSecurityGroupId'

  RDSSecurityGroupId:
    Description: 'RDS Security Group ID'
    Value: !GetAtt SecurityGroupsStack.Outputs.RDSSecurityGroupId
    Export:
      Name: !Sub '${ProjectName}-${Environment}-RDSSecurityGroupId'
