AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS MySQL Stack for Niigata Kaigo Subsystem - Production Environment'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Stack Dependencies'
        Parameters:
          - VPCStackName
          - SubnetsStackName
          - SecurityGroupsStackName
          - KMSStackName
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName
      - Label:
          default: 'RDS Configuration'
        Parameters:
          - DBInstanceClass
          - DBAllocatedStorage
          - DBName
          - DBMasterUsername
          - DBMasterPassword
          - MultiAZ
          - BackupRetentionPeriod
          - PreferredBackupWindow
          - PreferredMaintenanceWindow

Parameters:
  VPCStackName:
    Type: String
    Default: niigata-kaigo-prod-vpc-core-stack
    Description: Name of the VPC Core stack

  SubnetsStackName:
    Type: String
    Default: niigata-kaigo-prod-subnets-stack
    Description: Name of the Subnets stack

  SecurityGroupsStackName:
    Type: String
    Default: niigata-kaigo-prod-security-groups-stack
    Description: Name of the Security Groups stack

  KMSStackName:
    Type: String
    Default: niigata-kaigo-prod-kms-stack
    Description: Name of the KMS stack

  EnvironmentName:
    Type: String
    Default: production
    Description: Environment name

  ProjectName:
    Type: String
    Default: niigata-kaigo
    Description: Project name for tagging

  DBInstanceClass:
    Type: String
    Default: db.r6g.large
    Description: Database instance class
    AllowedValues:
      - db.t4g.micro
      - db.t4g.small
      - db.t4g.medium
      - db.t4g.large
      - db.r6g.large
      - db.r6g.xlarge
      - db.r6g.2xlarge

  DBAllocatedStorage:
    Type: Number
    Default: 100
    Description: Allocated storage in GB
    MinValue: 20
    MaxValue: 1000

  DBName:
    Type: String
    Default: niigatakaigo
    Description: Database name
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    MinLength: 1
    MaxLength: 64

  DBMasterUsername:
    Type: String
    Default: admin
    Description: Master username for the database
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    MinLength: 1
    MaxLength: 16

  DBMasterPassword:
    Type: String
    NoEcho: true
    Description: Master password for the database (8-41 characters)
    MinLength: 8
    MaxLength: 41

  MultiAZ:
    Type: String
    Default: 'true'
    Description: Enable Multi-AZ deployment
    AllowedValues:
      - 'true'
      - 'false'

  BackupRetentionPeriod:
    Type: Number
    Default: 7
    Description: Backup retention period in days
    MinValue: 1
    MaxValue: 35

  PreferredBackupWindow:
    Type: String
    Default: '17:00-18:00'
    Description: Preferred backup window (UTC)

  PreferredMaintenanceWindow:
    Type: String
    Default: 'sun:18:00-sun:19:00'
    Description: Preferred maintenance window (UTC)

Resources:
  # ========================================
  # DB Subnet Group
  # ========================================

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub '${ProjectName}-${EnvironmentName}-db-subnet-group'
      DBSubnetGroupDescription: Subnet group for RDS MySQL
      SubnetIds:
        - !ImportValue
          Fn::Sub: '${SubnetsStackName}-PrivateDBSubnet1aId'
        - !ImportValue
          Fn::Sub: '${SubnetsStackName}-PrivateDBSubnet1cId'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-db-subnet-group'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # DB Parameter Group
  # ========================================

  DBParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      DBParameterGroupName: !Sub '${ProjectName}-${EnvironmentName}-mysql8-params'
      Description: Custom parameter group for MySQL 8.0
      Family: mysql8.0
      Parameters:
        character_set_server: utf8mb4
        collation_server: utf8mb4_unicode_ci
        max_connections: '300'
        slow_query_log: '1'
        long_query_time: '2'
        log_queries_not_using_indexes: '1'
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-mysql8-params'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ========================================
  # RDS Instance
  # ========================================

  RDSInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-${EnvironmentName}-mysql'
      Engine: mysql
      EngineVersion: '8.0.43'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      StorageType: gp3
      StorageEncrypted: true
      KmsKeyId:
        Fn::ImportValue: !Sub '${KMSStackName}-RDSKeyId'
      Iops: 3000
      DBName: !Ref DBName
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref DBParameterGroup
      VPCSecurityGroups:
        - !ImportValue
          Fn::Sub: '${SecurityGroupsStackName}-RDSSecurityGroupId'
      MultiAZ: !Ref MultiAZ
      BackupRetentionPeriod: !Ref BackupRetentionPeriod
      PreferredBackupWindow: !Ref PreferredBackupWindow
      PreferredMaintenanceWindow: !Ref PreferredMaintenanceWindow
      CopyTagsToSnapshot: true
      EnableCloudwatchLogsExports:
        - error
        - general
        - slowquery
      AutoMinorVersionUpgrade: false
      PubliclyAccessible: false
      DeletionProtection: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-mysql'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  RDSInstanceId:
    Description: RDS Instance ID
    Value: !Ref RDSInstance
    Export:
      Name: !Sub '${AWS::StackName}-InstanceId'

  RDSEndpointAddress:
    Description: RDS Endpoint Address
    Value: !GetAtt RDSInstance.Endpoint.Address
    Export:
      Name: !Sub '${AWS::StackName}-EndpointAddress'

  RDSEndpointPort:
    Description: RDS Endpoint Port
    Value: !GetAtt RDSInstance.Endpoint.Port
    Export:
      Name: !Sub '${AWS::StackName}-EndpointPort'

  DBSubnetGroupName:
    Description: DB Subnet Group Name
    Value: !Ref DBSubnetGroup
    Export:
      Name: !Sub '${AWS::StackName}-SubnetGroupName'

  DBParameterGroupName:
    Description: DB Parameter Group Name
    Value: !Ref DBParameterGroup
    Export:
      Name: !Sub '${AWS::StackName}-ParameterGroupName'
