AWSTemplateFormatVersion: '2010-09-09'
Description: 'Transit Gateway - Hub and Spoke Network (Multi-VPC / Multi-Account support)'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - EnvironmentName
          - ProjectName
      - Label:
          default: 'Transit Gateway Configuration'
        Parameters:
          - AmazonSideAsn
          - AutoAcceptSharedAttachments
          - DefaultRouteTableAssociation
          - DefaultRouteTablePropagation
          - DnsSupport
          - VpnEcmpSupport

Parameters:
  EnvironmentName:
    Type: String
    Description: 'Environment name (dev, staging, production)'
    AllowedValues:
      - dev
      - staging
      - production
    Default: dev

  ProjectName:
    Type: String
    Description: 'Project name'
    Default: niigata-kaigo

  AmazonSideAsn:
    Type: Number
    Description: 'Amazon side ASN for Transit Gateway'
    Default: 64512
    MinValue: 64512
    MaxValue: 65534

  AutoAcceptSharedAttachments:
    Type: String
    Description: 'Auto accept shared attachments (for multi-account)'
    Default: enable
    AllowedValues:
      - enable
      - disable

  DefaultRouteTableAssociation:
    Type: String
    Description: 'Default route table association'
    Default: disable
    AllowedValues:
      - enable
      - disable

  DefaultRouteTablePropagation:
    Type: String
    Description: 'Default route table propagation'
    Default: disable
    AllowedValues:
      - enable
      - disable

  DnsSupport:
    Type: String
    Description: 'DNS support'
    Default: enable
    AllowedValues:
      - enable
      - disable

  VpnEcmpSupport:
    Type: String
    Description: 'VPN ECMP support'
    Default: enable
    AllowedValues:
      - enable
      - disable

Resources:
  # ==========================================================================
  # Transit Gateway
  # ==========================================================================
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: !Ref AmazonSideAsn
      AutoAcceptSharedAttachments: !Ref AutoAcceptSharedAttachments
      DefaultRouteTableAssociation: !Ref DefaultRouteTableAssociation
      DefaultRouteTablePropagation: !Ref DefaultRouteTablePropagation
      DnsSupport: !Ref DnsSupport
      VpnEcmpSupport: !Ref VpnEcmpSupport
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: ManagedBy
          Value: CloudFormation

  # ==========================================================================
  # Transit Gateway Route Tables
  # ==========================================================================

  # Common VPC用のRoute Table
  CommonRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-rt-common'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: common
        - Key: ManagedBy
          Value: CloudFormation

  # App VPC用のRoute Table
  AppRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      TransitGatewayId: !Ref TransitGateway
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${EnvironmentName}-tgw-rt-app'
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: !Ref ProjectName
        - Key: VPCType
          Value: app
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  TransitGatewayId:
    Description: 'Transit Gateway ID'
    Value: !Ref TransitGateway
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-TransitGatewayId'

  TransitGatewayArn:
    Description: 'Transit Gateway ARN'
    Value: !GetAtt TransitGateway.Id

  CommonRouteTableId:
    Description: 'Transit Gateway Route Table ID for Common VPC'
    Value: !Ref CommonRouteTable
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-TGW-CommonRouteTableId'

  AppRouteTableId:
    Description: 'Transit Gateway Route Table ID for App VPC'
    Value: !Ref AppRouteTable
    Export:
      Name: !Sub '${ProjectName}-${EnvironmentName}-TGW-AppRouteTableId'

  AmazonSideAsn:
    Description: 'Amazon side ASN'
    Value: !Ref AmazonSideAsn
